# Generated by Django 4.0 on 2021-12-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100),
        ),
    ]
