# Generated by Django 4.0 on 2021-12-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_statistic_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='clicks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
