# Generated by Django 4.0 on 2021-12-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_statistic_clicks_alter_statistic_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='cpc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='cpm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
